name: Deploy Func App

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
    - name: 'Login via Azure CLI'
      uses: Azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Setup Dotnet 2.2.300
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.300'
    - name: 'Run dotnet'
      shell: pwsh
      run: |
        # If your function app project is not located in your repository's root
        # Please change your directory for dotnet build in pushd
        pushd .
        dotnet build --configuration Release --output ./output
        popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1.1.0
      id: fa
      with:
        app-name: SPAFuncApp
#         publish-profile: ${{ secrets.SCM_CREDENTIALS }}
        package: './output'
